/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.bin.Usuario;
import model.dao.UsuarioDao;


public class TelaDadosUsuario extends javax.swing.JInternalFrame {

    DefaultListModel lista = new DefaultListModel();
    UsuarioDao objUsuarioDao = new UsuarioDao();
    
    public TelaDadosUsuario() {
        initComponents();       
        objUsuarioDao.readUsuario().forEach((usuario) -> {
            lista.addElement(usuario.getIdCadUsuario() +" - "+usuario.getNome());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexoEd = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        rdMasc = new javax.swing.JRadioButton();
        rdFemi = new javax.swing.JRadioButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNomes = new javax.swing.JList<>();
        lblIdUsuario = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("Nome :");

        jLabel2.setText("Email");

        jLabel3.setText("Sexo :");

        jLabel4.setText("Login");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        grupoSexoEd.add(rdMasc);
        rdMasc.setText("Mascolino");

        grupoSexoEd.add(rdFemi);
        rdFemi.setText("Feminino");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        lstNomes.setModel(lista);
        lstNomes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstNomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstNomesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstNomes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnEditar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNome))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdMasc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdFemi))
                                    .addComponent(txtEmail)
                                    .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))))
                    .addComponent(lblIdUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIdUsuario)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rdMasc)
                            .addComponent(rdFemi))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void lstNomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstNomesMouseClicked
        String user = lstNomes.getSelectedValue().trim();
        user = user.replace(" ", "");
        String dados[] = user.split("-"); 
        Usuario usuario = objUsuarioDao.readUsuarioUn(Integer.parseInt(dados[0]));
        txtNome.setText(usuario.getNome());
        txtEmail.setText(usuario.getEmail());
        if(usuario.getSexo() == 'M'){
            rdMasc.setSelected(true);
        }else{
            rdFemi.setSelected(true);
        }
        txtLogin.setText(usuario.getLogin());
        lblIdUsuario.setText(Integer.toString(usuario.getIdCadUsuario()));
        
        
    }//GEN-LAST:event_lstNomesMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String campos = "";
        
        if(txtNome.getText().equals("")){
            campos = campos + "Nome, ";
        }else{
        }
        
        if(txtEmail.getText().equals("")){
            campos = campos + "Email, ";
        }       
        
        if(!rdMasc.isSelected() && !rdFemi.isSelected()){
            campos = campos + "Sexo, ";
        }
        
        if(txtLogin.getText().equals("")){
            campos = campos + "Login, ";
        }
        
        if(!campos.equals("")){
            campos = "Os campos " + campos + " são obrigatórios.";
            JOptionPane.showMessageDialog(null, campos, "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }else{
            char charSexo;
            if(rdMasc.isSelected()){
                charSexo = 'M';
            }else{
                charSexo = 'F';
            }
            
            Usuario objUsuario = new Usuario(Integer.parseInt(lblIdUsuario.getText()), txtNome.getText(), txtEmail.getText(), charSexo, txtLogin.getText(), "");
            objUsuarioDao.update(objUsuario);
            
            lista.clear();
            
            objUsuarioDao.readUsuario().forEach((usuario)->{
                lista.addElement(usuario.getIdCadUsuario() +" - "+usuario.getNome());
            });
            
            
            JOptionPane.showMessageDialog(this, "Dados editados com sucesso!");
            
        }
        
         
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.ButtonGroup grupoSexoEd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdUsuario;
    private javax.swing.JList<String> lstNomes;
    private javax.swing.JRadioButton rdFemi;
    private javax.swing.JRadioButton rdMasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
